### ISSUE TITLE
NdkCompile is no longer supported

### ISSUE THREAD

**Issue by jianglove7** [nuttawutmalee/react-native-bluetooth-serial-next#30]
WARNING: The following project options are deprecated and have been removed:
android.useDeprecatedNdk
NdkCompile is no longer supported

**Comment by Naveen562117** [comment]
> WARNING: The following project options are deprecated and have been removed:
> android.useDeprecatedNdk
> NdkCompile is no longer supported

why did this issue is closed  i am getting the same error any help on this please
