### ISSUE TITLE
Calling connect method crashes application

### ISSUE THREAD

**Issue by LenoCode** [nuttawutmalee/react-native-bluetooth-serial-next#5]
**Describe the bug**
I'm having problem with connecting to arduino bluetooth module. After I call connect() method I get the message "Connected to 'bluetoothName'" but second after my application crash. When i get to the log I got two exception.
First one is 

> ObjectAlreadyConsumedException: Map already consumed
Exception is thrown at RCTBluetoothSerialModule at line 602 `params.putMap("device",device)`

Second one is

> java.io.IOException: bt socket closed, read return: -1
Exception is thrown at RCTBluetoothSerialService at line 436 `bytes = mmInStream.read(buffer);`

Maybe my setup or the way I'm using it is wrong. But for testing purpose I only scanned unpairedDevices and saved them in state. 
Added onPress listener on each device with method that goes like this

`
        const conn = await BleSerial.device(device.id).connect();
        console.log(conn);
    `

EDIT

I commented this part of code
`//        WritableMap params = Arguments.createMap();`
`//        params.putMap("device", device);`
`//        params.putString("message", msg);`
`//        sendEvent(CONN_SUCCESS, params);`

And it is not disconnecting me and I can send message

**Comment by nuttawutmalee** [comment]
246f7c386dcab75e719fbbf62ba87681f9ce402d solved in v1.2.3 *fingers crossed*
